Fix the preview formatting when a variable appears in a link url
cds-snc/notification-utils pull request #344
Opened 2024-12-31 21:50 UTC by smcmurtry

# Summary | Résumé

Draft for now

## Related Issues | Cartes liées

* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/614
* https://github.com/cds-snc/notification-planning/issues/783

# Test instructions | Instructions pour tester la modification

_TODO: Fill in test instructions for the reviewer._

# Release Instructions | Instructions pour le déploiement

None.

# Reviewer checklist | Liste de vérification du réviseur

- [ ] This PR does not break existing functionality.
- [ ] This PR does not violate GCNotify's privacy policies.
- [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
- [ ] This PR does not significantly alter performance.
- [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

2025-01-03 17:19 UTC, smcmurtry commented on tests/test_template.py
> +    )
fixed!

2025-01-06 13:27 UTC, andrewleith requested changes
LGTM - nice work!

I tested in the preview and the HTML is now valid!  

We can't test this in api yet though since API is still not updated to python 3.12.  So, I don't think we can bump api with this version of utils until that is done.

You still need to bump the version and update waffles (details [here](https://github.com/cds-snc/notification-utils/wiki/How-to-update-notification%E2%80%90utils))!

2025-01-06 16:23 UTC, smcmurtry commented on notifications_utils/field.py
> +    placeholder_pattern_for_link_url = re.compile(
thank you AI 🤖 😄

2025-01-06 18:48 UTC, andrewleith approved these changes
LGTM

2025-01-08 16:59 UTC, merged